---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    verify:
      package: "example"
      compose_file: "/opt/vmalert/docker-compose.yml"
      compose_line: '    image: "victoriametrics/vmalert:latest"'
      compose_owner: "homelab"
      compose_group: "homelab"
      compose_mode: "0640"
      config_file: "/opt/vmalert/alerts/alerts.yml"
      config_line: '# Alerts for various VM components'
      config_owner: "homelab"
      config_group: "homelab"
      config_mode: "0640"
      service_file: "/etc/systemd/system/vmalert.service"
      service_line: 'Description=vmalert service with docker compose'
      service_owner: "root"
      service_group: "root"
      service_mode: "0770"
      daemon: "vmalert"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_version }}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family }}"
          - "ansible_system  => {{ ansible_system }}"

    - name: "Check compose file {{ verify.compose_file }}"
      ansible.builtin.lineinfile:
        name: "{{ verify.compose_file }}"
        line: "{{ verify.compose_line }}"
        state: present
        owner: "{{ verify.compose_owner }}"
        group: "{{ verify.compose_group }}"
        mode: "{{ verify.compose_mode }}"
      check_mode: true
      register: molecule_compose
      failed_when: (molecule_compose is changed) or (molecule_compose is failed)

    - name: "Check alerts file {{ verify.config_file }}"
      ansible.builtin.lineinfile:
        name: "{{ verify.config_file }}"
        line: "{{ verify.config_line }}"
        state: present
        owner: "{{ verify.config_owner }}"
        group: "{{ verify.config_group }}"
        mode: "{{ verify.config_mode }}"
      check_mode: true
      register: molecule_alerts
      failed_when: (molecule_alerts is changed) or (molecule_alerts is failed)

    - name: "Check service file {{ verify.service_file }}"
      ansible.builtin.lineinfile:
        name: "{{ verify.service_file }}"
        line: "{{ verify.service_line }}"
        state: present
        owner: "{{ verify.service_owner }}"
        group: "{{ verify.service_group }}"
        mode: "{{ verify.service_mode }}"
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)

    - name: "Check daemon {{ verify.daemon }}"
      ansible.builtin.service:
        name: "{{ verify.daemon }}"
        state: started
        enabled: true
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)
